name: Development

on: [push, pull_request]

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}-latest
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - "3.1"
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - uses: kurocha/setup-cpp@master
    
    - name: Run tests
      timeout-minutes: 10
      run: |
        gem install teapot
        teapot fetch
        teapot build Executable/glslang
